### ISSUE TITLE
Errors when moving around a .spv file

### ISSUE THREAD

**Issue by RenatoUtsch** [kbenzie/vim-spirv#2]
I'm having the following errors when moving around a .spv file. This is making the plugin unusable.

On Vim:
```
Error detected while processing function spirv#highlight_extinst:
line   23:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing function spirv#highlight_extinst:
line   23:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing function spirv#highlight_extinst:
line   23:
  File "<string>", line 3, in find_group_names
Press ENTER or type command to continue
Error detected while processing function spirv#highlight_extinst:
line   23:
NameError: global name 'vim' is not defined
Press ENTER or type command to continue
Error detected while processing function spirv#highlight_extinst:
line   23:
E858: Eval did not return a valid python object
Press ENTER or type command to continue
Error detected while processing function spirv#highlight_extinst:
line   33:
E714: List required
Press ENTER or type command to continue
Error detected while processing function spirv#highlight_extinst:
line   45:
E714: List required
Press ENTER or type command to continue
```

On NeoVim:
```
Error detected while processing function spirv#highlight_extinst[23]..provider#python#Call:              
line   18:                                                                                               
error caught in request handler 'python_eval ('find_group_names()',)':                                   
Traceback (most recent call last):                                                                       
  File "/usr/lib/python2.7/site-packages/neovim/plugin/script_host.py", line 150, in python_eval         
    return eval(expr, self.module.__dict__)                                                              
  File "<string>", line 1, in <module>                                                                   
  File "<string>", line 3, in find_group_names                                                           
Press ENTER or type command to continue                                                                  
Error detected while processing function spirv#highlight_extinst[23]..provider#python#Call:              
line   18:                                                                                               
NameError: global name 'vim' is not defined                                                              
Press ENTER or type command to continue                                                                  
Error detected while processing function spirv#highlight_extinst:                                        
line   33:                                                                                               
E714: List required                                                                                      
Press ENTER or type command to continue                                                                  
Error detected while processing function spirv#highlight_extinst:                                        
line   45:                                                                                               
E714: List required                                                                                      
Press ENTER or type command to continue
```

**Comment by kbenzie** [comment]
Hi @RenatoUtsch, thanks for the bug report. This function is implemented in Python because I was lazy ideally it should be vimscript. I have Pyhton 2 compiled into my vim and do not get this error. Could you paste the result of `vim --version` so I can determine which configuration is required to reproduce this bug? I'm thinking either you have Python 3 or no Python at all.

In the mean time you have disable this feature by setting the following in you vimrc file, this should stop the error messages until I can push a fix.

```vim
let g:spirv_enable_extinst_error = "0"
```

**Comment by RenatoUtsch** [comment]
Hi,

I won't be able to post the output of my `vim --version` for the next 12
hours as I've just left home, but I know I'm using Python 3.

If you're not able to rewrite the code in VimScript, could you at least
make the code compatible with both python 2 and 3?

And thanks, I'll try the suggestion later today.

**Comment by kbenzie** [comment]
Okay since you know you are using Python 3 I don't need the output of `vim --version`. I should be able to make the code work with both versions of Python without too much trouble. Thanks.

**Comment by kbenzie** [comment]
@RenatoUtsch I beleive I have a fix for Python 3 support, if you could verify that the fix works for you and review the above PR I would be very grateful.

**Comment by RenatoUtsch** [comment]
I'll do that tonight. Thanks!

**Comment by RenatoUtsch** [comment]
Even by checking out your support_py3 branch it doesn't look like it's working.

This is the error with NeoVim:
```
Error detected while processing function spirv#highlight_extinst[25]..provider#python#Call:                                                                                                                         
line   18:                                                                                                                                                                                                          
error caught in request handler 'python_eval ('find_group_names()',)':                                                                                                                                              
Traceback (most recent call last):                                                                                                                                                                                  
  File "/usr/lib/python2.7/site-packages/neovim/plugin/script_host.py", line 150, in python_eval                                                                                                                    
    return eval(expr, self.module.__dict__)                                                                                                                                                                         
  File "<string>", line 1, in <module>                                                                                                                                                                              
  File "<string>", line 3, in find_group_names                                                                                                                                                                      
Press ENTER or type command to continue                                                                                                                                                                             
Error detected while processing function spirv#highlight_extinst[25]..provider#python#Call:                                                                                                                         
line   18:                                                                                                                                                                                                          
NameError: global name 'vim' is not defined                                                                                                                                                                         
Press ENTER or type command to continue                                                                                                                                                                             
Error detected while processing function spirv#highlight_extinst:                                                                                                                                                   
line   35:                                                                                                                                                                                                          
E714: List required                                                                                                                                                                                                 
Press ENTER or type command to continue                                                                                                                                                                             
Error detected while processing function spirv#highlight_extinst:                                                                                                                                                   
line   47:                                                                                                                                                                                                          
E714: List required                                                                                                                                                                                                 
Press ENTER or type command to continue
```

This is the error with Vim:
```
Error detected while processing function spirv#highlight_extinst:
line   25:
Traceback (most recent call last):
Error detected while processing function spirv#highlight_extinst:
line   25:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing function spirv#highlight_extinst:
line   25:
  File "<string>", line 3, in find_group_names
Press ENTER or type command to continue
Error detected while processing function spirv#highlight_extinst:
line   25:
NameError: global name 'vim' is not defined
Press ENTER or type command to continue
Error detected while processing function spirv#highlight_extinst:
line   25:
E858: Eval did not return a valid python object
Press ENTER or type command to continue
Error detected while processing function spirv#highlight_extinst:
line   35:
E714: List required
Press ENTER or type command to continue
Error detected while processing function spirv#highlight_extinst:
line   47:
E714: List required
Press ENTER or type command to continue
```

My `nvim --version`:
```
NVIM 0.1.7
Build type: Release
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.7/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

My `vim --version`:
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar  6 2017 14:13:23)
Included patches: 1-427
Compiled by Arch Linux
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     +tcl/dyn
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
-clientserver    +insert_expand   +packages        -toolbar
-clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl/dyn        +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python/dyn      +vreplace
+cscope          +lispindent      +python3/dyn     +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      +lua/dyn         +rightleft       +writebackup
+diff            +menu            +ruby/dyn        -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      -mouseshape      +startuptime     -xsmp
+eval            +mouse_dec       +statusline      -xterm_clipboard
+ex_extra        +mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro -L/usr/local/lib -Wl,--as-needed -o vim        -lm -lncurses -lelf -lnsl    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/core_perl/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lieee -lm     
```

**Comment by RenatoUtsch** [comment]
Looks like it's the same error.

**Comment by RenatoUtsch** [comment]
I won't accept/request changes to the code, as it looks like it's not the problem.

**Comment by kbenzie** [comment]
@RenatoUtsch thanks for the information, that fact that the `vim` Python module isn't found seems very strange to me. In any case I think the most portable solution is to remove the Python dependency and port the feature over to vimscript. I'll keep you posted.

**Comment by kbenzie** [comment]
@RenatoUtsch I've remove the Python dependency, hopefully it works for you this time.

**Comment by RenatoUtsch** [comment]
Yep! Working perfectly now!
